[package]
name = "porffor-wasip3-runtime-archive"
version = "0.1.0"
edition = "2024"
[lib]
path = "../src/lib.rs"
crate-type = ["staticlib"]
[features]
static-link = []
[dependencies]
wasip3 = "=0.8.0"
wit-bindgen = { version = "=0.60.0", features = ["macros"] }
futures = { version = "=0.3.31", default-features = false, features = ["async-await"] }
ryu-js = "=1.0.2"
[profile.release]
opt-level = "s"
panic = "abort"
