export const primitiveCases = [
  {name:'null-undefined',source:'console.log(null);console.log(undefined);let x;console.log(x);',expected:[null,undefined,undefined]},
  {name:'mixed-branch',source:'let x=2;if(true)x=null;console.log(x);if(false)x=8;else x=true;console.log(x);',expected:[null,true]},
  {name:'mixed-loop',source:'let x=null;for(let i=0;i<3;i++){console.log(x);if(i===0)x=4;else x=false;}console.log(x);',expected:[null,4,false,false]},
  {name:'mixed-function',source:'function f(x){if(x)return 42;return null;}console.log(f(true));console.log(f(false));',expected:[42,null],legacyStdout:'42\n\n',legacyIssue:'retained C print dispatch omits null returned from a mixed-type function'},
  {name:'polymorphic-identity',source:'function id(x){return x;}console.log(id(3));console.log(id(false));console.log(id(null));console.log(id(undefined));',expected:[3,false,null,undefined],legacyStdout:'3\nfalse\n\nundefined\n',legacyIssue:'retained C print dispatch omits null returned through a polymorphic identity function'},
  {name:'implicit-return',source:'function f(x){if(x)return 5;}console.log(f(false));console.log(f(true));',expected:[undefined,5]},
  {name:'empty-return',source:'function f(){return;}console.log(f());',expected:[undefined]},
  {name:'coercive-arithmetic',source:'console.log(true+2);console.log(null+4);console.log(undefined+1);console.log(false-true);console.log(true*5);console.log(null/false);',expected:[3,4,NaN,-1,5,NaN]},
  {name:'coercive-unary',source:'console.log(+true);console.log(-null);console.log(+undefined);console.log(-false);',expected:[1,-0,NaN,-0]},
  {name:'coercive-integer',source:'console.log(true<<2);console.log(undefined|3);console.log(~null);console.log(Math.imul(true,-7));console.log(null>>>0);',expected:[4,3,-1,-7,0]},
  {name:'primitive-comparisons',source:'console.log(null<true);console.log(false>=null);console.log(undefined<=0);console.log(true>0);console.log(NaN!==NaN);',expected:[true,true,false,true,true]},
  {name:'strict-type-equality',source:'console.log(null===undefined);console.log(false===0);console.log(true!==1);console.log(null===null);console.log(undefined===undefined);',expected:[false,false,true,true,true]},
  {name:'primitive-truthiness',source:'function f(x){if(x)return true;return false;}console.log(f(null));console.log(f(undefined));console.log(f(NaN));console.log(f(-0));console.log(f(-1));console.log(f(Infinity));',expected:[false,false,false,false,true,true]},
  {name:'postfix-converts-old-value',source:'let x=true;console.log(x++);console.log(x);x=null;console.log(x--);console.log(x);x=undefined;console.log(++x);',expected:[1,2,0,-1,NaN],legacyStdout:'true\n2\nnull\n-1\n1\n',legacyIssue:'retained C update expressions retain old nonnumeric types and increment undefined incorrectly'},
  {name:'shadowed-undefined',source:'{let undefined=7;console.log(undefined);}function f(undefined){return undefined;}console.log(f(false));',expected:[7,false],legacyFailure:"Uncaught SyntaxError: Identifier 'undefined' has already been declared\n",legacyIssue:'retained C rejects valid block-scoped shadowing of undefined'},
  {name:'shadowed-nan-infinity',source:'{let NaN=null;let Infinity=false;console.log(NaN);console.log(Infinity);}',expected:[null,false],legacyFailure:"Uncaught SyntaxError: Identifier 'NaN' has already been declared\n",legacyIssue:'retained C rejects valid block-scoped shadowing of NaN/Infinity'},
  {name:'mixed-parallel-edges',source:'let a=true;let b=null;for(let i=0;i<3;i++){let t=a;a=b;b=t;}console.log(a);console.log(b);',expected:[null,true]},
  {name:'recursive-mixed-result',source:'function f(x){if(x===0)return null;if(x===1)return true;return f(x-2);}console.log(f(6));console.log(f(7));',expected:[null,true]},
  {name:'unconstrained-unused-function',source:'function identity(x){return x;}console.log(9);',expected:[9]},
  {name:'initialization-order',source:'let x=null;let y=x;let z;z=y;console.log(z);',expected:[null]},
];
