export const stringCases = [
  {name:'literal-and-empty',source:'console.log("hello");console.log("");console.log("hello".length);console.log("".length);',expected:['hello','',5,0]},
  {name:'concatenation',source:'let a="ab";let b="cd";console.log(a+b);a+=b;console.log(a);',expected:['abcd','abcd']},
  {name:'length-and-call',source:'function join(a,b){return a+b;}console.log(join("ab","c").length);console.log(join("x","y"));',expected:[3,'xy']},
  {name:'content-equality',source:'let a="ab"+"cd";console.log(a==="abcd");console.log(a!=="abce");console.log("ab"==="abc");console.log(""==="");',expected:[true,true,false,true]},
  {name:'mixed-equality',source:'console.log("1"===1);console.log("false"===false);console.log(null==="null");console.log(undefined!=="undefined");',expected:[false,false,false,true]},
  {name:'string-truthiness',source:'function f(x){if(x)return true;return false;}console.log(f(""));console.log(f("0"));console.log(!"false");console.log(!"");',expected:[false,true,false,true]},
  {name:'mixed-plus',source:'console.log("x="+42);console.log(42+"=x");console.log(""+true);console.log(false+"!");console.log(""+null);console.log(undefined+"");',expected:['x=42','42=x','true','false!','null','undefined']},
  {name:'number-formatting',legacyStdout:"0\nNaN\nInfinity\n-Infinity\n1e-07\n1e+21\n100000000000000000000\n1e-06\n",legacyIssue:"Legacy C number-to-string uses padded exponents and exponential notation at 1e-6.",source:'console.log(""+-0);console.log(""+NaN);console.log(""+Infinity);console.log(""+-Infinity);console.log(""+1e-7);console.log(""+1e21);console.log(""+1e20);console.log(""+0.000001);',expected:['0','NaN','Infinity','-Infinity','1e-7','1e+21','100000000000000000000','0.000001']},
  {name:'plus-evaluation-order',legacyStdout:"bb\nbb\nbb\n",legacyIssue:"Legacy C reads the left operand after the right operand assignment.",source:'let x="a";console.log(x+(x="b"));x="a";x+=(x="b");console.log(x);console.log(x);',expected:['ab','ab','ab']},
  {name:'numeric-plus-in-string-module',source:'console.log("x");console.log(2+3);console.log(true+null);console.log(undefined+1);',expected:['x',5,1,NaN]},
  {name:'utf16-length',source:'console.log("é".length);console.log("😀".length);console.log("a😀b".length);console.log("\\ud800".length);console.log("\\udc00".length);',expected:[1,2,4,1,1]},
  {name:'surrogate-concatenation',legacyStdout:"=\u0000\ntrue\n2\n",legacyIssue:"Legacy C output truncates UTF-16 units to low bytes instead of encoding UTF-8.",source:'let s="\\ud83d"+"\\ude00";console.log(s);console.log(s==="😀");console.log(s.length);',expected:['😀',true,2]},
  {name:'lone-surrogates',legacyStdout:"\u0000\na\u0000b\nfalse\nfalse\n",legacyIssue:"Legacy C output truncates lone surrogate units to zero bytes.",source:'console.log("\\ud800");console.log("a\\udc00b");console.log("\\ud800"==="\\ud801");console.log("\\ud800"==="�");',expected:['\ud800','a\udc00b',false,false]},
  {name:'embedded-nul',legacyStdout:"a\n3\ntrue\nfalse\n",legacyIssue:"Legacy C byte-string output ends at embedded NUL.",source:'let s="a\0b";console.log(s);console.log(s.length);console.log(s==="a\0b");console.log(s==="a");',expected:['a\0b',3,true,false]},
  {name:'unicode-content',legacyStdout:"\u0011J;30@8O <\ufffd<\ufffd\nfalse\n2\n",legacyIssue:"Legacy C output truncates UTF-16 units to low bytes instead of encoding UTF-8.",source:'console.log("България"+" 🇧🇬");console.log("é"==="e\u0301");console.log("e\u0301".length);',expected:['България 🇧🇬',false,2]},
  {name:'mixed-branches',source:'function f(x){if(x)return "yes";return 2;}console.log(f(true));console.log(f(false));console.log("answer="+f(false));',expected:['yes',2,'answer=2']},
  {name:'growing-loop',source:'let s="";for(let i=0;i<40;i++)s+="x";console.log(s.length);console.log(s);',expected:[40,'x'.repeat(40)]},
  {name:'parallel-string-edges',source:'let a="a";let b="b";for(let i=0;i<3;i++){let t=a;a=b;b=t;}console.log(a);console.log(b);',expected:['b','a']},
  {name:'recursive-retention',source:'function f(n,s){if(n===0)return s;let keep=s+"x";let later=f(n-1,keep);console.log(keep);return later;}console.log(f(3,"a"));',expected:['axxx','axx','ax','axxx']},
  {name:'retained-across-allocations',source:'let keep="keep"+" me";for(let i=0;i<200;i++){let garbage="trash"+i;}console.log(keep);console.log(keep==="keep me");',expected:['keep me',true]},
  {name:'shadowed-locals',source:'let s="outer";{let s="inner";console.log(s);}console.log(s);',expected:['inner','outer']},
  {name:'empty-concat',source:'console.log(""+"");console.log((""+"").length);console.log((""+"a")===("a"+""));',expected:['',0,true]},
];
